# .streamlit/config.toml
[theme]
base="light"
primaryColor="#7C3AED"           # paars (modern)
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F6F7FB"
textColor="#111827"
font="sans serif"                 # gebruiken we met Inter via CSS
